name: Jest API automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm install
      - name: Run tests and generate HTML report
        run: npm test
      - name: Save HTML test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-test-report
          path: reporter/reportResult.html
          retention-days: 7